#!/usr/bin/env python3

DANETLSA_IMAP = 10
DANETLSA_POP3 = 20
DANETLSA_SMTP = 30
DANETLSA_TLS  = 40
DANETLSA_PEM  = 50
DANETLSA_DER  = 60
DANETLSA_FTP  = 70

DANETLS_protocols = [DANETLSA_IMAP, DANETLSA_POP3, DANETLSA_SMTP,
                     DANETLSA_TLS,  DANETLSA_PEM,  DANETLSA_DER,
                     DANETLSA_FTP]